services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - .env.local
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./api/src:/app/
    ports:
      - 127.0.0.1:8080:8080
    depends_on:
      db:
        condition: service_healthy
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    env_file:
      - .env.local
    command: >-
      -c "config_file=/etc/postgresql/postgresql.conf"
    volumes:
      - ./db/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./db/data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 3s
      retries: 5
  redis:
    image: "redis"
    ports:
      - "6379:6379"
    volumes:
      - "./redis/data/redis:/data"
